# Generated by Django 5.1 on 2024-08-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubUserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('user_id', models.IntegerField(unique=True)),
                ('node_id', models.CharField(max_length=100)),
                ('avatar_url', models.URLField()),
                ('gravatar_id', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField()),
                ('html_url', models.URLField()),
                ('followers_url', models.URLField()),
                ('following_url', models.URLField()),
                ('gists_url', models.URLField()),
                ('starred_url', models.URLField()),
                ('subscriptions_url', models.URLField()),
                ('organizations_url', models.URLField()),
                ('repos_url', models.URLField()),
                ('events_url', models.URLField()),
                ('received_events_url', models.URLField()),
                ('user_type', models.CharField(max_length=50)),
                ('site_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
